/**
 *
 * PassphraseJS-lib, version 0.1.0, MIT license
 * 
 * 1. Creates random passphrases from words in a dictionary
 * 
 *   pass = Passphrase.random( [keylen [, dictionary]] )
 *     keylen: # bytes in equivalent numeric key
 *     dictionary: array of words
 * 
 *   Passphrase.randomNum is the random number generator used (returns 
 *   number between 0 and 1, Math.random is default).
 * 
 * 2. Creates passphrases from numeric keys and vise-versa (follows rfc1751)
 * 
 *   pass = Passphrase.fromKey( key [, dictionary] )
 *   key = Passphrase.toKey( pass [, keylen [, dictionary]] )
 *     key: a numeric byte array of length keylen
 * 
 * For all functions:
 *
 *   keylen: if ommitted or null, 32 bytes (256 bits) is used 
 *   dictionary: if omitted, Passphrase.defaultDictionary is used
 *
 * Example: a 32 byte key and 8K (8192) word dictionary will produce 20 
 * word passphrase (13 bits per word).
 * 
 * dictionary.length should be a power of 2, otherwise some of the words
 * will not be used.  For example, only the first 4K words will be used 
 * from a dictionary containing 6K words.
 * 
 * The default dictionary included here is an 8K common short word 
 * extraction of Alan Beale's "2 of 12" public domain dictionary.
 *
 * Test tool, custom dictionary creation tool:
 *   https://github.com/secure-passphrase
 *
 */

var Passphrase = {};


/**
 * Return a random passphrase string
 */
Passphrase.random = function( keylen, dictionary ) { 
  return Passphrase.fromKey( Passphrase.randomKey(keylen), dictionary );
}


/**
 * Return a random key (byte array) of length (# bytes)
 */
Passphrase.randomKey = function( keylen ) {
  keylen = keylen ? keylen : 32;
  var key = [], rand = Passphrase.randomNum;
  for( var i=0,r; i<keylen; i++ )
    key.push( Math.round(rand()*255) );
  return key;
}


/**
 * Determine random number generator (internal)
 */
Passphrase.randomNum =
function() {
  var rand = Math.random;
  /*try {  //TODO: auto-detect secureRandom available
    if (typeof(SecureRandom.random) == 'function') 
      rand = SecureRandom.random;
  } catch(e) {rand = Math.random;}*/
  return rand;
}();


/**
 * Select passphrase from dictionary using bits in numeric key
 *
 *   key: byte array of arbitrary length
 *   dictionary: array of between 2 and < 2^16 words
 */
Passphrase.fromKey = function( key, dictionary ) {
  dictionary = dictionary ? dictionary : Passphrase.defaultDictionary;
  var bitsperword = Passphrase.calcBitsPerWord( dictionary );
  var wordsinpass = Math.ceil( (key.length*8) / bitsperword );
  //  use bits in key to select words from dict
  var pass = "";
  for( var i=0; i<wordsinpass; i++ )
    pass += (i?' ':'') + 
            dictionary[Passphrase.unpackKeyBits(key,i*bitsperword,bitsperword)];
  return pass;
}


/**
 * Calculate numeric key from passphrase
 *
 *   keylen: # bytes in key
 *   dictionary: array of between 2 and < 2^16 words
 */
Passphrase.toKey = function( pass, keylen, dictionary ) {
  dictionary = dictionary ? dictionary : Passphrase.defaultDictionary;
  var bitsperword = Passphrase.calcBitsPerWord( dictionary );
  var words = pass.split( ' ' );
  var bitsneeded = words.length * bitsperword;
  //  0 key
  var key = [];
  for( var i=0,n; i<keylen; i++ ) key.push( 0 );
  //  pack word indexes into key
  for( i=0; i<words.length; i++ ) {
    n = Passphrase.getWordIndex( words[i], dictionary );
    if (n < 0)
      throw new Error( "Passphrase contains words not in dictionary" );
    Passphrase.packKeyBits( key, n, i*bitsperword, bitsperword );
  }
  return key;
}


/**
 * Get index of word in dict, -1 if not found
 */
Passphrase.getWordIndex = function( word, dictionary ) {
  dictionary = dictionary ? dictionary : Passphrase.defaultDictionary;
  for( i=0; i<dictionary.length; i++ )
    if (dictionary[i] == word)
      return i;
  return -1;
}


/**
 * Calc #bits needed to select a word from dict
 */
Passphrase.calcBitsPerWord = function( dictionary ) {
  dictionary = dictionary ? dictionary : Passphrase.defaultDictionary;
  if (dictionary.length < 2 || dictionary.length > (0xffff+1))
    throw new Error( "Dictionary invalid" );
  var wordcount = dictionary.length;
  var bitsperword = 0;
  for( var wn=1; wn<wordcount; wn*=2,bitsperword++ );
  if (wn > wordcount) bitsperword--;
  return bitsperword;
}


/**
 * Get unsigned int from series of bits in byte array (16 bit max)
 */
Passphrase.unpackKeyBits = function( arr, startbit, bitcount ) {
  if (bitcount > 16)
    throw new Error( "Bitcount exceeds maximum" );
  //  make int from three bytes containing the target bits
  var startbyte = new Number( startbit / 8 );
  startbyte = Math.floor( startbyte );
  var byte1 = startbyte >= arr.length ? 0 : arr[startbyte];
  startbyte++;
  var byte2 = startbyte >= arr.length ? 0 : arr[startbyte];
  startbyte++;
  var byte3 = startbyte >= arr.length ? 0 : arr[startbyte];
  var w = (byte1<<16) | (byte2<<8) | byte3;
  //  align/strip bits
  w <<= (startbit % 8);
  w &= 0x00FFFFFF;
  w >>= 24 - bitcount;
  //var debuglook = w.toString( 2 );
  return w;
}


/**
 * Put unsigned int into series of bits in byte array (16 bit max)
 */
Passphrase.packKeyBits = function( arr, n, startbit, bitcount ) {
  if (bitcount > 16)
    throw new Error( "Bitcount exceeds maximum" );
  //  line up bits
  n <<= 24 - bitcount;
  n >>= startbit % 8;
  //  create mask
  for( var i=0,mask=0; i<bitcount; i++ ) mask |= 1 << i;
  mask <<= 24 - bitcount;
  mask >>= startbit % 8;
  mask = (~mask) & 0x00FFFFFF;
  //  combine with bytes already there
  var startbyte = Math.floor( new Number(startbit/8) );
  if (startbyte < arr.length)
    arr[startbyte] &= (mask>>16) & 0x000000FF,
    arr[startbyte] |= (n>>16) & 0x000000FF;
  startbyte++;
  if (startbyte < arr.length)
    arr[startbyte] &= (mask>>8) & 0x000000FF,
    arr[startbyte] |= (n>>8) & 0x000000FF;
  startbyte++;
  if (startbyte < arr.length)
    arr[startbyte] &= mask & 0x000000FF,
    arr[startbyte] |= n & 0x000000FF;
}


/**
 * Convert key to hexcode string
 */
Passphrase.keyToHex = function( key ) {
  for( var i=0,hex="",h; i<key.length; i++ )
    h = key[i].toString( 16 ),
    hex += h.length>1 ? h : ('0'+h);
  return hex;
}


/**
 * Convert hexcode string to key
 */
Passphrase.keyFromHex = function( hex ) {
  if (hex.length%2) hex += '0';
  for( var i=0,key=[]; i<hex.length; i+=2 )
    key.push( parseInt(hex.substr(i,2),16) );
  return key;
}


/**
 * An 8K extraction from Beale's 2 of 12 dictionary (common short words)
 */
Passphrase.beale_dictionary_13bit = Passphrase.defaultDictionary = //8192 words
["a","aback","abacus","abandon","abate","abbey","abdomen","abduct",
"abhor","abide","ability","abject","ablaze","able","abnormal","aboard",
"abound","about","above","abrasive","abreast","abridge","abroad","abrupt",
"abscess","absence","absent","absentee","absolute","absolve","absorb","abstract",
"absurd","abundant","abuse","abusive","abyss","academic","accent","accept",
"access","acclaim","accord","accost","account","accuracy","accurate","accuse",
"accuser","accustom","ace","ache","achieve","acid","acidity","acne",
"acoustic","acquaint","acquire","acquit","acre","acrid","acrobat","across",
"act","acting","action","activate","active","activity","actor","actual",
"acute","acutely","ad","adage","adamant","adapt","add","addict",
"addition","additive","address","adept","adequate","adhere","adherent","adhesive",
"adjacent","adjoin","adjourn","adjunct","adjust","admiral","admire","admit",
"adobe","adopt","adoption","adorable","adore","adorn","adrift","adroit",
"adroitly","adult","advance","adverb","adverse","advice","advise","advisory",
"advocate","aerial","afar","affable","affair","affect","affinity","affirm",
"affix","afflict","affluent","afford","afloat","afraid","after","again",
"against","age","agency","agenda","agent","aghast","agile","agility",
"agitate","agitator","ago","agony","agree","ahead","aid","aide",
"ailment","aim","aimless","air","aircraft","airfield","airline","airmail",
"airplane","airport","airtight","airy","aisle","ajar","akin","alarm",
"alas","albino","album","alcohol","alcove","ale","alert","algae",
"algebra","alias","alibi","alien","alienate","align","alimony","alive",
"all","allege","allergic","allergy","alley","alliance","allot","allow",
"alloy","allude","allusion","ally","almanac","almond","almost","alms",
"aloft","alone","along","aloof","aloud","already","also","altar",
"alter","altitude","alto","altruism","aluminum","always","am","amass",
"amateur","amaze","ambition","amble","ambush","amend","amends","amenity",
"American","amiable","amicable","amid","amiss","ammonia","amnesia","among",
"amount","ample","amplify","amply","amputate","amuse","an","analysis",
"analyst","anatomy","ancestor","ancestry","anchor","ancient","and","anecdote",
"anemia","anew","angel","anger","angle","angler","angrily","angry",
"anguish","angular","animal","animate","ankle","annals","annex","announce",
"annoy","annual","annually","annuity","annul","anoint","another","answer",
"ant","antenna","antennae","anthem","anthill","antidote","antique","antler",
"antonym","anvil","anxiety","anxious","any","anybody","anyhow","anything",
"anyway","anywhere","apart","apathy","ape","aperture","apex","apiece",
"apology","apostle","appall","apparel","apparent","appeal","appear","appease",
"append","appendix","applaud","applause","apple","apply","appoint","appraise",
"approach","approve","apricot","April","apron","apt","aptitude","aquarium",
"aquatic","aqueduct","arable","arbiter","arc","arcade","arch","archaic",
"archway","ardent","ardently","ardor","arduous","are","area","arena",
"argue","arid","arise","arm","armchair","armor","armory","armpit",
"army","aroma","aromatic","arose","around","arouse","arrange","array",
"arrest","arrival","arrive","arrogant","arrow","arsenic","arson","art",
"artery","artisan","artist","as","asbestos","ascend","ascent","ascribe",
"ash","ashamed","ashen","ashore","ashtray","Asian","aside","ask",
"askance","askew","asleep","aspect","asphalt","aspire","aspirin","ass",
"assassin","assault","assembly","assent","assert","assess","asset","assign",
"assist","assorted","assume","assure","asterisk","asteroid","asthma","astonish",
"astound","astray","astride","astute","astutely","asylum","at","ate",
"atheist","athletic","atom","atomic","attach","attack","attain","attempt",
"attend","attest","attic","attire","attitude","attract","auburn","auction",
"audible","audibly","audience","audit","audition","auditor","augment","August",
"aunt","aura","austere","author","auto","automate","autumn","autumnal",
"avail","avarice","avenge","avenue","average","averse","aversion","avert",
"aviation","avid","avoid","avow","avowal","await","awake","award",
"aware","away","awe","awful","awfully","awhile","awkward","awning",
"awoke","awry","axes","axiom","axis","axle","babble","babe",
"baboon","baby","bachelor","back","backbone","backer","backfire","backward",
"bacon","bacteria","bad","badge","badger","badly","baffle","bag",
"bagel","baggage","baggy","bail","bait","bake","bakery","balance",
"bald","bale","balk","ball","ballad","ballet","balloon","ballot",
"ballroom","balmy","bamboo","ban","banana","band","bandit","banish",
"banister","banjo","bank","banker","banking","banner","banquet","banter",
"baptize","bar","barbaric","barbecue","barber","bare","barely","bargain",
"barge","baritone","bark","barley","barn","barnacle","barnyard","barrage",
"barrel","barren","barrier","barring","barter","base","basement","bases",
"bash","bashful","basic","basin","basis","bask","basket","bass",
"bassoon","bat","batch","bath","bathe","bathroom","baton","batter",
"battery","battle","bawl","bay","bazaar","be","beach","beacon",
"bead","beagle","beak","beaker","beam","bean","bear","beard",
"bearing","beast","beat","beater","beauty","became","beckon","become",
"bed","bedlam","bedroom","bedside","bedtime","bee","beech","beef",
"been","beer","beet","beetle","befit","before","befriend","beg",
"began","beggar","begin","begrudge","begun","behalf","behave","behavior",
"behead","behind","behold","beige","being","belch","belief","believe",
"belittle","bell","bellow","belly","belong","below","belt","bench",
"bend","beneath","benign","bent","bequeath","bequest","beret","berry",
"berth","beset","beside","besides","best","bestow","bet","betray",
"better","between","beverage","beware","beyond","bias","bib","bicker",
"bicycle","bid","biennial","big","bike","bile","bill","billion",
"billow","bin","bind","binder","binding","bingo","biology","biped",
"biplane","birch","bird","birth","birthday","biscuit","bisect","bishop",
"bison","bit","bitch","bite","bitter","bizarre","blab","black",
"blacken","blacktop","bladder","blade","blame","blanch","blank","blanket",
"blare","blast","blaze","bleach","bleak","bled","bleed","blemish",
"blend","bless","blessing","blew","blight","blimp","blind","blink",
"bliss","blissful","blithe","blizzard","blob","block","blockade","blond",
"blood","bloody","bloom","blossom","blot","blotch","blotter","blouse",
"blow","blowout","blue","bluebird","bluff","blunder","blunt","blur",
"blurt","blush","boar","board","boarder","boast","boat","bob",
"bobsled","bodice","bodily","body","bog","boil","boiler","bold",
"boldly","boldness","bolster","bolt","bomb","bombard","bomber","bond",
"bondage","bone","bonfire","bonnet","bonus","bony","boo","book",
"booklet","bookmark","boom","boon","boost","booster","boot","booth",
"booty","border","bore","boredom","born","borne","borough","borrow",
"bosom","boss","bossy","botanist","botany","botch","both","bother",
"bottle","bottom","bough","bought","boulder","bounce","bound","bounty",
"bouquet","bout","bow","bowl","bowling","box","boxer","boy",
"boycott","boyhood","boyish","bra","brace","bracelet","bracket","brackish",
"brag","braggart","braid","brain","brainy","brake","bran","branch",
"brand","brandy","brass","brat","brave","bravery","brawl","brawn",
"brawny","bray","brazen","breach","bread","breadth","break","breast",
"breath","breathe","breather","breed","breeder","breeze","breezy","brevity",
"brew","brewery","bribe","bribery","brick","bridal","bride","bridge",
"bridle","brief","bright","brighten","brim","brine","bring","brisk",
"briskly","bristle","brittle","broach","broad","broadly","broccoli","broil",
"broke","broken","broker","bronco","bronze","brooch","brood","brook",
"broom","broth","brother","brought","brow","brown","browse","bruise",
"brunt","brush","brutal","brutally","brute","brutish","bubble","buck",
"bucket","buckle","bud","buddy","budge","budget","buff","buffalo",
"buffet","bug","bugle","build","building","built","bulb","bulbous",
"bulge","bulk","bulky","bull","bullet","bulletin","bullion","bully",
"bum","bump","bumper","bun","bunch","bundle","bungalow","bungle",
"bunion","bunk","bunny","buoy","buoyancy","buoyant","burden","bureau",
"burglar","burial","burly","burn","burner","burnish","burrow","burst",
"bury","bus","bush","bushel","bushy","busily","business","bust",
"bustle","busy","busybody","but","butler","butt","butter","button",
"buttress","buxom","buy","buyer","buzz","buzzard","buzzer","by",
"bygone","bypass","byway","cab","cabbage","cabin","cabinet","cable",
"caboose","cache","cackle","cactus","cadence","cadet","cafe","caffeine",
"cage","cagey","cajole","cake","calamity","calcium","calculus","calendar",
"calf","caliber","calico","call","caller","calling","callous","callus",
"calm","calorie","calves","came","camel","camera","camp","camper",
"campus","can","canal","cancel","cancer","candid","candle","candor",
"candy","cane","canine","canister","cannery","cannibal","cannon","canoe",
"canopy","can't","canteen","canter","canvas","canvass","canyon","cap",
"capable","capacity","cape","caprice","capsize","capsule","captain","caption",
"captor","capture","car","caramel","carat","caravan","carbon","carcass",
"card","cardiac","cardinal","care","career","carefree","careful","careless",
"caress","cargo","caribou","carnage","carnival","carol","carp","carpet",
"carriage","carrot","carry","cart","carton","cartoon","carve","cascade",
"case","cash","cashew","cashier","cashmere","casket","cassette","cast",
"castaway","caste","casting","castle","castrate","casual","casually","casualty",
"cat","catapult","catch","catching","catchy","category","cater","caterer",
"catfish","catholic","catnap","catnip","cattle","catwalk","caught","cause",
"caustic","caution","cautious","cavalry","cave","cavern","cavity","cavort",
"cease","cedar","cede","ceiling","celery","cell","cellar","cello",
"Celsius","cement","censor","censure","census","cent","center","central",
"century","ceramic","cereal","cerebral","ceremony","certify","chafe","chain",
"chair","chalet","chalk","chamber","champ","chance","change","channel",
"chant","chaos","chaotic","chap","chapel","chapter","char","charcoal",
"charge","chariot","charity","charm","charming","chart","charter","chase",
"chasm","chassis","chaste","chasten","chastise","chastity","chat","chatter",
"chatty","cheap","cheapen","cheaply","cheat","check","checkers","cheek",
"cheer","cheery","cheese","chef","chemical","chemist","cherish","cherry",
"cherub","chess","chest","chestnut","chew","chewy","chic","Chicano",
"chick","chicken","chide","chief","chiefly","child","childish","children",
"chili","chill","chilly","chime","chimney","chin","china","chink",
"chip","chipmunk","chirp","chisel","chivalry","choice","choir","choke",
"choose","choosy","chop","chopper","choppy","choral","chord","chore",
"chorus","chose","chosen","chow","chowder","christen","chrome","chromium",
"chronic","chubby","chuck","chuckle","chug","chum","chunk","chunky",
"church","chute","cider","cigar","cinch","cinder","cinema","cinnamon",
"cipher","circuit","circular","circus","cistern","citation","cite","citizen",
"citrus","city","civic","civics","civil","civilian","clack","claim",
"clam","clamber","clammy","clamor","clamp","clan","clang","clank",
"clap","clarinet","clarity","clash","clasp","class","classic","classify",
"clause","claw","clay","clean","cleaner","clear","clearing","clearly",
"cleat","cleavage","cleaver","clef","cleft","clemency","clench","clergy",
"clerical","clerk","clever","cleverly","click","client","cliff","climate",
"climax","climb","climber","clinch","cling","clinic","clink","clip",
"clipping","clique","cloak","clock","clod","clog","close","closet",
"closure","clot","cloth","clothe","clothes","clothing","cloud","cloudy",
"clove","clown","club","cluck","clue","clumsily","clung","clutch",
"clutter","coach","coal","coarse","coast","coastal","coat","coax",
"cob","cobbler","cobra","cobweb","cocaine","cock","cockeyed","cockpit",
"cocky","cocoa","coconut","cocoon","cod","code","coerce","coffee",
"coffin","cog","coil","coin","coincide","colander","cold","coldness",
"colic","collage","collapse","collar","collect","college","collide","collie",
"colon","colonel","colonial","colony","color","colored","colorful","colossal",
"colt","column","coma","comb","combat","combine","come","comedy",
"comet","comfort","comic","comical","comma","command","commando","commence",
"commend","comment","commerce","commit","common","commune","commute","commuter",
"compact","company","compare","compass","compel","compete","compile","complain",
"complete","complex","comply","compose","composer","compound","compress","comprise",
"compute","computer","comrade","con","concave","conceal","concede","conceit",
"conceive","concept","concern","concert","concise","concrete","concur","condemn",
"condense","conduct","cone","confer","confide","confine","conflict","confound",
"confront","congeal","congress","conifer","connect","conquer","conquest","consent",
"conserve","consign","consist","console","consort","conspire","construe","consul",
"consult","consume","consumer","contain","contest","continue","contort","contour",
"contract","contrary","contrast","contrite","control","convene","convent","converse",
"convert","convex","convey","convict","convince","convulse","coo","cook",
"cookie","cool","coop","cop","cope","copious","copper","copy",
"coral","cord","corduroy","core","cork","corn","cornea","corner",
"corny","corps","corpse","corral","correct","corridor","corrode","corsage",
"cosmetic","cosmic","cosmos","cost","costly","costume","cot","cottage",
"cotton","couch","cougar","cough","could","council","counsel","count",
"counter","country","county","couple","coupon","courage","course","court",
"courtesy","cousin","cove","covenant","cover","coverage","covert","covet",
"covetous","cow","coward","cowardly","cowboy","cower","cowgirl","coy",
"coyote","cozy","crab","crabby","crack","cracker","crackle","cradle",
"craft","craggy","cram","cramp","crane","cranium","crank","cranky",
"crash","crate","crater","crawl","crayfish","crayon","craze","crazy",
"creak","creaky","cream","creamy","crease","create","creation","creative",
"creature","credible","credit","creditor","creed","creek","creep","creepy",
"cremate","crepe","crept","crest","crevice","crew","crib","cricket",
"crime","criminal","crimson","cringe","crinkle","cripple","crises","crisis",
"crisp","critic","critical","croak","crochet","crock","crocus","crony",
"crook","crooked","croon","crop","croquet","cross","crossbow","crossing",
"crotch","crouch","crow","crowd","crown","crucial","crucifix","crucify",
"crude","crudely","cruel","cruelty","cruise","crumb","crumble","crumple",
"crunch","crusade","crush","crust","crutch","cry","crystal","cub",
"cube","cubic","cuckoo","cucumber","cuddle","cue","cuff","cull",
"cultural","culture","cunning","cup","cupboard","curable","curb","curd",
"curdle","cure","curfew","curious","curl","currant","currency","current",
"curry","curse","curt","curtail","curtain","curtsy","curve","custom",
"customer","cut","cute","cuticle","cutlery","cutlet","cutting","cyanide",
"cycle","cyclone","cylinder","cymbal","cyst","czar","dab","dabble",
"dad","dagger","daily","daintily","dainty","dairy","daisy","dally",
"dam","damage","dame","damn","damp","dampen","dampness","dance",
"dandy","danger","dangle","dank","dare","daring","dark","darken",
"darkness","darling","darn","dart","dash","data","date","daub",
"daughter","daunt","dawdle","dawn","day","daybreak","daydream","daylight",
"daytime","daze","dazzle","deacon","dead","deaden","deadline","deadlock",
"deadly","deaf","deal","dean","dear","dearly","dearth","death",
"deathbed","debase","debate","debility","debit","debris","debt","debtor",
"debut","decade","decanter","decay","deceit","deceive","decency","decent",
"decently","decide","decided","decimal","decipher","decision","decisive","deck",
"declare","decline","decode","decorate","decorum","decoy","decrease","decree",
"decrepit","dedicate","deduct","deed","deep","deepen","deeply","deer",
"deface","defeat","defect","defend","defense","defer","defiance","defiant",
"deficit","defile","define","definite","deflate","deflect","deform","defraud",
"defrost","deft","deftly","defy","degrade","degree","deign","deity",
"delay","delete","delicacy","delicate","delight","delirium","deliver","delivery",
"deluge","delusion","deluxe","delve","demand","demean","demeanor","demented",
"demerit","demolish","demon","demote","demure","den","denial","denim",
"denote","denounce","dense","densely","density","dent","dental","dentist",
"deny","depart","depend","depict","deport","deposit","depot","depress",
"depth","deputy","derail","deride","derive","descend","descent","describe",
"desert","deserve","design","desire","desist","desk","desolate","despair",
"despise","despite","despot","dessert","destiny","destroy","detach","detached",
"detail","detain","detect","deter","detest","detour","detract","develop",
"device","devil","devise","devoid","devote","devoted","devour","devout",
"devoutly","dew","diabetes","diabetic","diagnose","diagonal","dial","dialect",
"diameter","diamond","diaper","diarrhea","diary","dice","dictate","diction",
"did","die","diet","differ","dig","digest","digit","dignity",
"dilate","dilemma","diligent","dilute","dilution","dim","dime","diminish",
"dimple","din","dine","diner","dinghy","dingy","dinner","dip",
"diploma","diplomat","dire","direct","directly","dirt","dirty","disagree",
"disarm","disaster","disband","discard","discern","disciple","disclaim","disclose",
"discolor","discord","discreet","discus","discuss","disdain","disease","disfavor",
"disgrace","disguise","disgust","dish","dishonor","disk","dislike","dislodge",
"disloyal","dismal","dismay","dismiss","dismount","disown","dispatch","dispel",
"dispense","disperse","displace","display","disposal","dispose","dispute","disrupt",
"dissect","dissent","dissolve","dissuade","distance","distant","distaste","distend",
"distill","distinct","distort","distract","district","ditch","dither","dive",
"diverse","divert","divide","dividend","divine","division","divorce","divulge",
"dizzy","do","docile","dock","doctor","doctrine","document","dodge",
"doe","does","dog","dogged","doghouse","dogma","dogmatic","dogwood",
"doldrums","dole","doleful","doll","dollar","dolly","dolphin","domain",
"dome","domestic","dominant","dominate","dominion","domino","donate","donation",
"done","donor","doodle","doom","door","doorstep","dope","dormant",
"dorsal","dose","dot","dote","double","doubt","doubtful","dough",
"doughnut","dour","douse","dove","dowdy","down","downfall","downhill",
"downpour","downtown","downy","dowry","doze","dozen","drab","draft",
"drafty","drag","dragon","drain","drainage","drama","dramatic","drank",
"drape","drapery","drastic","draw","drawer","drawl","drawn","dread",
"dreadful","dream","dreamer","dreamy","dredge","dregs","drench","dress",
"dresser","dressing","drew","dribble","drift","drill","drink","drinker",
"drip","drive","driven","driver","drizzle","drone","drool","droop",
"drop","drought","drove","drown","drowsy","drudge","drug","drum",
"drummer","drunk","drunken","dry","dual","dub","duck","duckling",
"duct","dud","dude","due","duel","duet","dug","dugout",
"duke","dull","duly","dumb","dumbbell","dummy","dump","dumpy",
"dunce","dune","dung","dungeon","dunk","dupe","duplex","durable",
"duration","during","dusk","dust","dusty","Dutch","dutiful","duty",
"dwarf","dwell","dwelling","dwindle","dye","dying","dynamic","dynamite",
"dynamo","dynasty","each","eager","eagerly","eagle","ear","eardrum",
"early","earn","earnest","earnings","earring","earth","earthly","earthy",
"ease","easel","easily","east","Easter","easterly","eastern","eastward",
"easy","eat","eaten","ebb","ebony","echo","eclair","eclipse",
"ecology","economic","economy","ecstatic","eczema","edge","edible","edict",
"edifice","edit","edition","editor","educate","eel","eerie","effect",
"effort","e.g.","egg","eggplant","eight","eighth","eighty","either",
"eject","elapse","elastic","elbow","elderly","elect","election","elective",
"electric","electron","elegance","elegant","element","elephant","elevate","elevator",
"eleven","eleventh","elf","eligible","elk","elm","elongate","elope",
"eloquent","else","elude","elusive","elves","embalm","embargo","embark",
"embassy","embed","ember","embezzle","emblem","embody","emboss","embryo",
"emerald","emerge","emigrant","emigrate","eminent","emit","emotion","emperor",
"emphases","emphasis","emphatic","empire","employ","employer","empower","empress",
"empty","emulate","enable","enact","enamel","enclose","encore","encroach",
"encumber","end","endanger","endear","endeavor","ending","endive","endless",
"endorse","endow","endure","enemy","energy","enforce","engage","engine",
"engineer","engrave","engulf","enhance","enigma","enjoy","enlarge","enlist",
"enliven","enmity","enormous","enough","enrage","enrich","enroll","ensemble",
"ensue","ensure","entangle","enter","enthrall","entice","entire","entirely",
"entirety","entitle","entreat","entreaty","entrust","entry","entwine","envelope",
"envious","envoy","envy","enzyme","epic","epidemic","episode","epoch",
"equal","equality","equally","equator","equinox","equip","era","erase",
"eraser","erect","erode","erosion","err","errand","error","erupt",
"escapade","escape","escort","Eskimo","essay","essence","estate","esteem",
"estimate","etch","eternal","ether","ethereal","ethical","ethnic","evacuate",
"evade","eve","even","event","ever","evermore","every","everyday",
"everyone","evict","evidence","evident","evil","evoke","evolve","ewe",
"exact","exactly","exalt","examine","excavate","exceed","excel","except",
"excess","exchange","excite","exclaim","exclude","excrete","excuse","execute",
"exempt","exercise","exert","exhale","exhaust","exhibit","exhort","exile",
"exist","exit","exotic","expand","expanse","expect","expel","expend",
"expense","expert","expire","explain","explicit","explode","exploit","explore",
"exponent","export","expose","exposure","express","extend","extent","external",
"extinct","extol","extra","extract","extreme","exult","eye","eyeball",
"eyebrow","eyelash","eyelid","eyesight","eyesore","fable","fabric","fabulous",
"facade","face","facet","facial","facility","fact","factor","factual",
"faculty","fad","fade","fail","failing","failure","faint","fair",
"fairly","fairy","faith","faithful","fake","falcon","fall","fallacy",
"fallout","false","falsify","falter","fame","family","famine","famous",
"fan","fanatic","fancy","fang","fantasy","far","faraway","fare",
"farewell","farm","fascism","fascist","fashion","fast","fasten","fat",
"fatal","fatality","fatally","fate","fateful","father","fatherly","fathom",
"fatigue","fatten","fatty","faucet","fault","faulty","fauna","favor",
"favorite","fawn","fear","fearful","feasible","feast","feat","feathery",
"February","feces","federal","fee","feeble","feed","feel","feeler",
"feeling","feet","feign","feint","feline","fell","fellow","felon",
"felony","felt","female","feminine","fence","fencing","fend","fender",
"fern","ferret","ferry","fertile","fervent","fervor","fester","festival",
"festive","fetch","fetter","fetus","feud","feudal","fever","feverish",
"few","fez","fiasco","fib","fibber","fiber","fickle","fiction",
"fiddle","fidelity","fidget","fidgety","field","fiend","fiendish","fierce",
"fiercely","fiery","fiesta","fifteen","fifth","fifty","fig","fight",
"figure","filament","filch","file","fill","fillet","filly","film",
"filter","filth","filthy","fin","final","finale","finality","finally",
"finance","finch","find","fine","finger","finicky","finish","finite",
"fir","fire","firearm","firefly","fireman","firewood","firm","first",
"fish","fishery","fishy","fission","fissure","fist","fit","fitful",
"fitness","fitting","five","fix","fixture","fizz","fizzle","flabby",
"flag","flagrant","flagship","flail","flair","flake","flaky","flame",
"flank","flannel","flap","flapjack","flare","flash","flashy","flask",
"flat","flatly","flatten","flatter","flattery","flaunt","flavor","flaw",
"flea","fleck","flee","fleece","fleet","flesh","fleshy","flew",
"flex","flexible","flick","flicker","flier","flight","flighty","flimsy",
"flinch","fling","flint","flip","flippant","flipper","flirt","flit",
"float","flock","flog","flood","floor","flooring","flop","floppy",
"flora","floral","florist","floss","flounce","flour","flourish","flout",
"flow","flower","flowery","flown","flu","flue","fluency","fluent",
"fluff","fluffy","fluid","flung","flunk","flurry","flush","flute",
"fly","foal","foam","foamy","focus","fodder","foe","fog",
"foggy","foghorn","foible","foil","fold","folder","foliage","folk",
"folklore","follow","follower","folly","fond","fondle","fondly","fondness",
"font","food","fool","foolish","foot","football","foothill","foothold",
"footing","footpath","footstep","footwork","for","forage","foray","forbear",
"forbid","force","forceful","forceps","forcible","forcibly","ford","fore",
"forearm","forecast","forehead","foreign","foreman","foremost","foresee","forest",
"foretell","forever","forfeit","forgave","forge","forger","forgery","forget",
"forgo","forgot","fork","form","formal","formally","former","formerly",
"formless","formula","forsake","forsaken","forsook","fort","forth","fortress",
"fortune","forty","forum","fossil","foster","fought","foul","found",
"founder","foundry","fountain","four","fourteen","fourth","fowl","fox",
"foxy","foyer","fracas","fraction","fracture","fragile","fragment","fragrant",
"frail","frailty","frame","frank","frankly","frantic","fraud","fraught",
"fray","freak","freckle","free","freedom","freely","freeway","freeze",
"freezer","freight","frenzied","frenzy","frequent","fresh","freshen","freshly",
"freshman","fret","fretful","friar","friction","Friday","friend","friendly",
"fright","frighten","frigid","frill","frilly","fringe","frisky","frog",
"frolic","from","frond","front","frontier","frost","frosty","froth",
"frothy","frown","froze","frozen","frugal","fruit","fruitful","fruity",
"fry","fudge","fuel","fugitive","fulfill","full","fumble","fume",
"fumigate","fun","function","fund","funeral","fungi","funnel","funny",
"fur","furious","furl","furnace","furnish","furrow","furry","furtive",
"fury","fuse","fuselage","fusion","fuss","fussy","futile","future",
"fuzz","fuzzy","gable","gadget","gag","gaiety","gain","gait",
"gala","galactic","galaxy","gale","gall","gallant","gallery","galley",
"gallon","gallop","gallows","gamble","gambler","game","gander","gang",
"gangrene","gangster","gap","gape","garage","garb","garbage","garden",
"gardener","gargle","gargoyle","garish","garland","garlic","garment","garnet",
"garnish","garrison","garter","gas","gash","gasp","gate","gather",
"gaudy","gauge","gaunt","gauntlet","gauze","gave","gavel","gawky",
"gay","gaze","gazelle","gazette","gear","geese","gelatin","gem",
"gender","gene","genera","general","generate","generous","genesis","genetic",
"genial","genius","gentle","gently","gentry","genuine","genus","geology",
"geometry","geranium","germ","gesture","get","geyser","ghastly","ghetto",
"ghost","ghostly","giant","giddy","gift","gig","giggle","gild",
"gill","gin","ginger","gingerly","gingham","giraffe","girder","girdle",
"girl","girth","gist","give","given","glacial","glacier","glad",
"glade","gladly","glance","gland","glare","glaring","glass","glaze",
"gleam","glee","glib","glibly","glide","glider","glimmer","glimpse",
"glint","gloat","global","globe","globular","globule","gloom","gloomy",
"glorify","glorious","glory","gloss","glossary","glossy","glove","glow",
"glower","glucose","glue","glum","glut","glutton","gluttony","gnarled",
"gnash","gnat","gnaw","gnome","go","goad","goal","goat",
"gobble","goblet","goblin","godchild","goddess","godlike","godly","godsend",
"gold","golden","golf","golfer","gondola","gone","gong","good",
"goodness","goof","goofy","goose","gore","gorge","gorgeous","gory",
"gospel","gossip","got","gotten","gouge","gourd","gourmet","govern",
"governor","gown","grab","grace","gracious","grade","gradual","graduate",
"graft","grain","gram","grammar","grand","grandeur","grandly","grandson",
"granite","grant","grape","graph","graphic","graphite","grasp","grasping",
"grass","grassy","grate","grateful","gratify","grating","grave","gravel",
"gravity","gravy","gray","graze","grease","greasy","great","greed",
"greedy","green","greenery","greet","greeting","grenade","grew","grid",
"griddle","grief","grieve","grievous","grill","grim","grimace","grime",
"grimly","grimy","grin","grind","grip","grisly","gristle","grit",
"grits","gritty","groan","grocer","groggy","groin","groom","groove",
"grope","gross","grotto","grouch","ground","group","grouse","grove",
"grovel","grow","grower","growl","grown","growth","grub","grubby",
"grudge","gruel","grueling","gruesome","gruff","grumpy","grunt","guard",
"guardian","guess","guest","guffaw","guidance","guide","guild","guile",
"guilt","guiltily","guilty","guitar","gulch","gulf","gull","gully",
"gulp","gum","gummy","gumption","gun","gunman","gunshot","gurgle",
"gush","gusher","gust","gusty","gut","gutter","guy","gym",
"gymnast","gyrate","ha","habit","habitat","hack","hacksaw","had",
"haddock","hag","haggard","haggle","hail","hair","haircut","hairdo",
"hairy","hale","half","hall","halo","halt","halter","halve",
"halves","ham","hammer","hammock","hamper","hand","handbag","handcuff",
"handful","handicap","handle","handler","handout","handsome","handy","hang",
"hangar","hanger","hangover","hanker","happen","happily","happy","harangue",
"harass","harbor","hard","harden","hardly","hardship","hardware","hardwood",
"hardy","hare","hark","harm","harmful","harmless","harmony","harness",
"harp","harpoon","harsh","harshly","harvest","has","hash","hassle",
"haste","hasten","hasty","hat","hatch","hatchet","hate","hateful",
"hatred","haughty","haul","haunt","have","haven","havoc","hawk",
"hay","haywire","hazard","haze","hazel","hazy","he","head",
"headache","heading","headline","headlong","headway","heal","healer","health",
"healthy","heap","hear","hearing","hearsay","hearse","heart","hearten",
"hearth","heartily","hearty","heat","heater","heathen","heave","heaven",
"heavenly","heavy","hectic","hedge","heed","heedless","heel","hefty",
"heifer","height","heighten","heir","heirloom","held","helium","hell",
"hello","helm","helmet","help","helper","helpful","helping","helpless",
"hem","hemlock","hemp","hen","hence","henchman","her","herald",
"herb","herd","here","hereby","heredity","herein","heresy","heretic",
"herewith","heritage","hermit","hero","heroic","heroin","heroine","heroism",
"heron","herring","hers","herself","hesitant","hesitate","hew","hexagon",
"heyday","hiccup","hid","hidden","hide","hideous","high","highly",
"highway","hike","hilarity","hill","hilly","hilt","him","himself",
"hind","hinder","hinge","hint","hip","hippie","hire","his",
"hiss","historic","history","hit","hitch","hither","hitherto","hive",
"hives","hoard","hoarder","hoarse","hoax","hobble","hobby","hobo",
"hockey","hoe","hog","hoist","hold","holder","holdup","hole",
"holiday","holler","hollow","holly","holster","holy","homage","home",
"homeland","homeless","homely","homeward","homework","homicide","homonym","hone",
"honest","honesty","honey","honk","honor","hood","hoof","hook",
"hoop","hoot","hop","hope","hopeful","horde","hormone","horn",
"hornet","horny","horribly","horrid","horrify","horror","horse","hose",
"hospital","host","hostage","hostel","hostess","hostile","hot","hotbed",
"hotel","hotly","hound","hour","hourly","house","housing","hovel",
"hover","how","however","howl","hub","hubbub","huddle","hue",
"huff","huffy","hug","huge","hulk","hull","hum","human",
"humane","humanity","humble","humdrum","humid","humidify","humility","humor",
"humorist","humorous","hump","hunch","hundred","hung","hunger","hungrily",
"hungry","hunk","hunt","hunter","hurdle","hurl","hurry","hurt",
"hurtful","hurtle","husband","hush","husk","husky","hustle","hustler",
"hut","hutch","hybrid","hydrant","hydrogen","hyena","hygiene","hygienic",
"hymn","hymnal","hyphen","hysteria","ice","iceberg","icicle","icing",
"icy","idea","ideal","ideally","identify","identity","idiocy","idiom",
"idiot","idiotic","idle","idol","i.e.","if","igloo","ignite",
"ignition","ignorant","ignore","iguana","ill","illegal","illicit","illness",
"illusion","image","imagine","imbecile","imitate","immature","immerse","imminent",
"immobile","immoral","immortal","immune","immunity","immunize","imp","impact",
"impair","impale","impart","impeach","impede","impel","imperial","imperil",
"impish","implant","implicit","implore","imply","impolite","import","impose",
"imposing","impotent","impound","impress","imprint","imprison","improper","improve",
"impudent","impure","impurity","in","inane","inbred","incense","inch",
"incident","incision","incisor","incite","incline","include","income","incubate",
"incur","indebted","indecent","indeed","indent","index","Indian","indicate",
"indict","indirect","induce","induct","industry","inept","inert","inertia",
"inexact","infamous","infamy","infancy","infant","infantry","infect","infer",
"inferior","infest","infidel","infinite","infinity","infirm","inflate","inflict",
"inform","informal","informer","infrared","infuse","inhabit","inhale","inherent",
"inherit","inhibit","inhuman","inhumane","initial","initiate","inject","injure",
"injury","ink","inkling","inland","inlet","inmate","inn","inner",
"inning","innocent","inquest","inquire","inquiry","insane","inscribe","insect",
"insecure","insert","inside","insider","insight","insignia","insipid","insist",
"insolent","inspect","inspire","install","instance","instant","instead","instep",
"instill","instinct","instruct","insulin","insult","insure","intact","integral",
"intend","intense","intent","inter","intercom","interest","intern","interval",
"intimacy","intimate","into","intrude","intruder","inundate","invade","invader",
"invalid","invasion","invent","inventor","inverse","invert","invest","investor",
"invite","inviting","invoice","invoke","involved","inward","inwardly","iodine",
"iota","irate","iris","irk","iron","ironic","irony","irrigate",
"irritant","irritate","Islam","island","isle","issue","isthmus","it",
"itch","itchy","item","itemize","itself","ivory","ivy","jab",
"jabber","jack","jackal","jackass","jacket","jackpot","jade","jagged",
"jaguar","jail","jailer","jalopy","jam","jamboree","jangle","janitor",
"January","jar","jargon","jaunt","jaunty","javelin","jaw","jazz",
"jealous","jealousy","jeer","jelly","jerk","jerky","jersey","jest",
"jester","jet","jettison","jetty","Jew","jewel","jeweler","jewelry",
"Jewish","jibe","jiffy","jig","jiggle","jingle","jinx","jitters",
"jittery","job","jockey","jog","join","joint","joke","joker",
"jolly","jolt","jostle","jot","journey","jovial","joy","joyful",
"joyous","joyously","jubilant","judge","jug","juggle","juggler","juice",
"juicy","July","jumble","jumbo","jump","jumper","June","jungle",
"junior","junk","juror","jury","just","justify","jut","juvenile",
"kangaroo","kayak","keel","keen","keep","keeping","keepsake","keg",
"kennel","kept","kernel","kerosene","kettle","key","keyboard","khaki",
"kick","kid","kidnap","kidney","kill","killer","kiln","kilo",
"kilogram","kilowatt","kilt","kimono","kin","kind","kindle","kindly",
"kindness","kindred","king","kingdom","kink","kiss","kit","kitchen",
"kite","kitten","kitty","kiwi","knack","knapsack","knead","knee",
"kneecap","kneel","knelt","knew","knickers","knife","knight","knit",
"knives","knob","knock","knocker","knoll","knot","knotty","know",
"knowing","koala","lab","label","labor","lace","lacerate","lack",
"lacquer","lacy","lad","ladder","laden","ladle","lady","ladybug",
"lag","lagoon","laid","lain","lair","lake","lamb","lame",
"lament","lamp","lance","landing","landlady","landlord","landmark","lane",
"language","languid","languish","lanky","lantern","lap","lapel","lapse",
"larceny","lard","large","lark","larva","larvae","larynx","laser",
"lash","last","latch","late","lately","latent","lateral","latex",
"lather","latitude","latter","laugh","laughter","launch","laurel","lava",
"lavender","lavish","law","lawful","lawless","lawn","lawsuit","lawyer",
"lax","laxative","lay","layer","layman","layout","lazy","lead",
"leader","leaf","leaflet","leafy","league","leak","lean","leap",
"leapfrog","learn","lease","leash","least","leather","leave","leaves",
"lecture","led","ledge","leech","leek","leer","leery","left",
"leg","legacy","legal","legality","legalize","legend","legion","leisure",
"lemon","lend","length","lengthen","lengthy","lens","lentil","leopard",
"less","lessen","lesser","lesson","let","letter","lettuce","levee",
"level","lever","levy","liable","liar","libel","liberal","liberate",
"library","lice","license","lick","licorice","lid","lie","life",
"lifeboat","lifeless","lifelike","lifetime","lift","ligament","light","lighten",
"likable","like","likely","liken","likeness","likewise","liking","lilac",
"lilt","lily","limb","lime","limerick","limit","limp","line",
"lineage","linear","linen","linger","liniment","lining","link","linoleum",
"lint","lion","lip","lipstick","liquefy","liquid","liquor","lisp",
"list","listen","listener","listless","lit","liter","literal","literary",
"literate","lithe","litter","little","live","lively","liven","liver",
"lives","livid","living","lizard","llama","load","loaf","loan",
"loath","loathe","loathing","loaves","lob","lobby","lobe","lobster",
"local","locality","locate","location","lock","locker","locket","locust",
"lodge","loft","lofty","log","logic","logical","loiter","loll",
"lollipop","lone","lonely","lonesome","long","longhand","look","lookout",
"loom","loop","loophole","loose","loosen","loot","lope","lord",
"lore","lose","loser","loss","lost","lot","lotion","lottery",
"loud","lounge","louse","lovable","love","lovely","lover","loving",
"low","lower","lowly","loyal","lucid","lucky","lug","luggage",
"lukewarm","lull","lumber","lump","lunar","lunatic","lunch","luncheon",
"lung","lunge","lurch","lure","lurid","lurk","luscious","lush",
"luster","lustrous","luxury","lying","macaroni","machete","machine","mackerel",
"mad","made","madly","madness","magazine","maggot","magic","magical",
"magician","magnet","magnetic","magnolia","mahogany","maid","maiden","mail",
"mailbox","mailman","maim","main","mainland","mainly","maintain","majestic",
"majesty","major","majority","make","malady","malaria","male","malice",
"malign","mallard","mallet","malt","mammal","mammoth","man","manage",
"manager","mane","maneuver","mange","manger","mangle","mango","manhole",
"manhood","mania","maniac","manicure","manifest","manifold","mankind","manly",
"manner","manor","mansion","mantel","mantle","manual","manure","many",
"map","maple","mar","marathon","marble","March","march","mare",
"margin","marina","marine","mariner","marital","maritime","mark","marked",
"marker","market","maroon","marriage","marrow","marry","marsh","marshal",
"mart","martyr","marvel","mascot","mash","mask","mason","masonry",
"mass","massage","massive","mast","master","mastery","mat","match",
"mate","material","matinee","matron","matter","mattress","mature","maul",
"mauve","maxim","maximum","May","may","mayor","maze","me",
"meadow","meager","meal","mean","meander","meant","meantime","measles",
"measly","measure","meat","mechanic","medal","meddle","media","medical",
"medicine","mediocre","meditate","medium","medley","meek","meekly","meekness",
"meet","meeting","mellow","melody","melon","melt","member","membrane",
"memento","memorial","memorize","memory","men","menace","mend","menial",
"mental","mentally","menthol","menu","meow","merchant","merciful","mercy",
"mere","merely","merge","merger","meridian","meringue","merit","mermaid",
"merry","mesh","mess","message","met","metal","metallic","metaphor",
"mete","meteor","meteoric","meter","method","metric","mettle","mice",
"microbe","midday","middle","midget","midnight","midriff","midst","might",
"mighty","mike","mild","mildew","mile","mileage","militia","milk",
"milky","mill","milliner","million","mimic","mince","mind","mindful",
"mine","miner","mineral","mingle","minimize","minimum","minister","mink",
"minnow","minor","minstrel","mint","minus","minute","miracle","mirage",
"mire","mirror","mirth","mischief","miser","misery","misfit","mishap",
"mislead","misplace","misprint","misread","miss","missile","missing","mist",
"mistake","mistaken","mistook","mistress","misty","mite","mitt","mitten",
"mix","mixture","moan","moat","mob","mobile","mobilize","moccasin",
"mock","mode","model","modern","modest","modesty","modify","module",
"mohair","moist","moisture","molar","molasses","mold","moldy","mole",
"molecule","molest","mollify","mollusk","molt","molten","mom","moment",
"momentum","monarch","monarchy","monastic","Monday","monetary","money","mongrel",
"monitor","monk","monkey","monogram","monsoon","monster","month","moo",
"mood","moody","moon","moonbeam","moor","moose","mop","mope",
"moral","morale","morass","morbid","more","moreover","moron","morphine",
"morsel","mortal","mortally","mortify","mosaic","mosque","mosquito","moss",
"mossy","most","mostly","motel","moth","mother","motherly","motion",
"motivate","motive","motley","motor","motorist","motto","mound","mount",
"mountain","mourn","mourner","mournful","mourning","mouse","mouth","mouthful",
"movable","move","movement","mover","movie","mow","mower","Mr.",
"Mrs.","Ms.","much","muck","mucous","mucus","mud","muddle",
"muddy","muff","muffin","muffle","mug","muggy","mulch","mule",
"multiple","multiply","mumble","mummy","mumps","munch","mural","murder",
"murderer","murky","murmur","muscle","muse","museum","mush","mushroom",
"mushy","music","musical","musk","musket","muss","mussel","must",
"mustache","mustang","mustard","muster","musty","mutation","mute","mutilate",
"mutinous","mutiny","mutter","mutton","mutual","muzzle","my","myriad",
"myself","mystery","mystify","myth","mythical","nab","nag","nail",
"naive","naively","naivete","naked","name","nameless","namely","namesake",
"nap","nape","napkin","narrate","narrow","narrowly","nasal","nastily",
"nasty","nation","national","native","natural","nature","naught","naughty",
"nausea","nauseate","nauseous","nautical","naval","navel","navigate","navy",
"near","nearby","nearly","neat","neatly","neatness","neck","necklace",
"necktie","nectar","need","needle","needless","negative","neglect","neigh",
"neighbor","neither","neon","nephew","nerve","nervous","nest","nestle",
"net","network","neuter","neutral","neutron","never","new","newcomer",
"newly","news","newscast","newsy","next","nibble","nice","nicely",
"niche","nick","nickel","nickname","nicotine","niece","night","nightly",
"nil","nimble","nine","nineteen","ninety","ninth","nip","nipple",
"nippy","nit","nitrate","nitwit","no","nobility","noble","nobleman",
"nobly","nobody","nod","node","noise","noisy","nomad","nomadic",
"nominal","nominate","nominee","none","nonsense","noodle","nook","noon",
"noose","nor","norm","normal","normally","north","nose","nostril",
"nosy","not","notable","notably","notation","notch","note","notebook",
"nothing","notice","notify","notion","noun","nourish","novel","novelist",
"novelty","novice","now","nowadays","nowhere","noxious","nozzle","nuclear",
"nuclei","nucleus","nude","nudge","nudity","nugget","nuisance","numb",
"number","numeral","numerous","nun","nuptial","nurse","nursery","nurture",
"nut","nutrient","nutty","nuzzle","nylon","nymph","oak","oar",
"oases","oasis","oath","oatmeal","obedient","obese","obey","obituary",
"object","obligate","oblige","obliging","oblique","oblivion","oblong","oboe",
"obscene","observe","observer","obsess","obsolete","obstruct","obtain","obtuse",
"obvious","occasion","occupant","occupy","occur","ocean","o'clock","October",
"octopus","odd","oddity","odds","ode","odor","of","off",
"offend","offense","offer","offering","offhand","office","official","offing",
"offset","offshoot","offshore","often","ogle","ogre","oh","oil",
"oily","old","olive","omelet","omen","ominous","omit","on",
"once","oncoming","one","onion","onlooker","only","onrush","onset",
"onto","onward","ooze","opal","opaque","open","opening","opera",
"operate","opinion","opium","opossum","opponent","oppose","opposite","oppress",
"optic","optical","optician","optimism","optimist","optimum","option","optional",
"or","oral","orange","orator","oratory","orbit","orchard","orchid",
"ordain","ordeal","order","ordinary","ore","organ","organic","organism",
"organize","orient","origin","original","ornament","ornate","ornately","orphan",
"orthodox","ostrich","other","otter","ounce","our","ours","oust",
"out","outbreak","outclass","outcome","outcry","outdated","outdo","outdoor",
"outdoors","outer","outfield","outfit","outgoing","outgrow","outing","outlast",
"outlaw","outlay","outlet","outlook","outlying","outmoded","outpost","outrage",
"outrun","outset","outshine","outside","outsider","outsmart","outstrip","outward",
"outweigh","outwit","oval","ovary","ovation","oven","over","overall",
"overcast","overcoat","overcome","overdo","overdone","overdose","overdue","overflow",
"overhaul","overhead","overhear","overland","overlap","overload","overlook","overpass",
"overrate","overrule","overrun","overseas","oversee","overstep","overt","overtake",
"overtime","overtly","overture","overturn","overwork","owe","owl","own",
"owner","ox","oxen","oxidize","oxygen","oyster","pace","pacify",
"pack","package","packet","pact","pad","padding","paddle","paddock",
"paddy","padlock","pagan","page","pageant","pagoda","paid","pail",
"pain","painful","painless","paint","pair","pajamas","pal","palace",
"palate","pale","palette","pall","pallid","pallor","palm","paltry",
"pamper","pamphlet","pan","pancake","pancreas","panda","pane","panel",
"pang","panic","panorama","pansy","pant","panther","pantry","papa",
"papal","papaya","paper","par","parable","parade","paradise","paradox",
"paraffin","parakeet","paralyze","parasite","parasol","parcel","pardon","pare",
"parent","parish","park","parka","parkway","parlor","parole","parrot",
"parsley","parsnip","part","partial","particle","parting","partisan","partly",
"partner","party","pass","passable","passage","passion","Passover","passport",
"password","past","paste","pastel","pastor","pastoral","pastry","pasture",
"pat","patch","patent","paternal","path","pathetic","pathway","patience",
"patient","patio","patriot","patrol","patron","patter","pattern","patty",
"pause","pave","pavement","pavilion","paw","pawn","pay","payable",
"payment","payroll","pea","peace","peaceful","peach","peacock","peak",
"peal","peanut","pear","pearl","peasant","peat","pebble","pecan",
"peck","peculiar","pedal","peddle","peddler","pedigree","peek","peel",
"peep","peer","peerless","peg","pelican","pellet","pelt","pen",
"penal","penalize","penalty","pencil","pendant","pending","pendulum","penguin",
"penis","pennant","penny","pension","pensive","peon","people","pep",
"pepper","per","perceive","percent","perch","perfect","perform","perfume",
"perhaps","peril","perilous","period","periodic","perish","perk","perky",
"permeate","permit","peroxide","person","perspire","persuade","pert","pertain",
"peruse","pervade","perverse","pest","pester","pet","petal","petite",
"petition","petrify","petty","petulant","pew","pewter","phantom","pharmacy",
"phase","pheasant","phobia","phone","phonetic","phrase","physical","physics",
"physique","pianist","piano","pick","picket","pickle","picnic","picture",
"pie","piece","pier","pierce","piety","pig","pigeon","pigment",
"pigtail","pike","pile","pilfer","pill","pillar","pillow","pilot",
"pimple","pimply","pin","pinch","pine","pinion","pink","pinnacle",
"pint","pioneer","pious","pipe","piping","piracy","pirate","pistol",
"piston","pit","pitch","pitcher","piteous","pitfall","pitiful","pity",
"pivot","pizza","placard","place","plague","plaid","plain","plan",
"plane","planet","plank","plankton","plant","planter","plaque","plasma",
"plaster","plastic","plate","plateau","platinum","platoon","platter","play",
"player","playmate","playpen","plaza","plea","plead","pleasant","please",
"pleasure","pleat","pledge","plenty","pliable","pliers","plight","plod",
"plot","plow","pluck","plug","plum","plumage","plumbing","plume",
"plump","plunder","plunge","plural","plus","plush","ply","plywood",
"poach","pocket","pod","poem","poet","poetic","poetry","point",
"pointed","poise","poison","poke","poker","polar","pole","police",
"policy","polish","polite","politely","politics","polka","poll","pollen",
"pollute","polo","polygon","polyp","pomp","pompous","poncho","pond",
"ponder","pontoon","pony","poodle","pool","poor","poorly","pop",
"popcorn","poplar","poppy","populace","populate","porch","pore","pork",
"porous","porpoise","port","portable","portent","porter","porthole","portion",
"portrait","portray","pose","position","positive","possess","possible","possibly",
"post","postage","postal","poster","postman","postmark","postpone","posy",
"pot","potato","potent","pothole","potion","potter","pottery","pouch",
"poultry","pounce","pound","pour","pout","poverty","powder","powdery",
"power","powerful","practice","prairie","praise","prance","prank","prawn",
"pray","prayer","preach","preacher","preamble","precede","precious","precise",
"predator","preen","preface","prefer","prefix","prelude","premiere","premium",
"prepare","presence","present","preserve","preside","press","pressing","pressure",
"presume","pretend","pretense","pretty","prevail","preview","previous","prey",
"price","prick","prickle","prickly","pride","priest","prim","primate",
"prime","primer","primeval","primly","prince","princess","print","printer",
"prior","priority","prism","prison","prisoner","privacy","private","prize",
"pro","probable","probably","probe","problem","proceed","proceeds","process",
"proclaim","procure","prod","prodigal","prodigy","product","profane","profess",
"profile","profit","profound","profuse","progeny","program","prohibit","project",
"prolific","prom","prompt","promptly","prone","prong","pronoun","proof",
"prop","propel","proper","properly","property","prophecy","prophesy","prophet",
"proposal","propose","prose","prospect","prosper","protect","protein","proton",
"protrude","proud","prove","provide","provoke","prow","prowl","prowler",
"proxy","prude","prudish","prune","pry","psalm","puberty","public",
"pucker","pudding","puddle","pudgy","puff","puffy","pull","pulley",
"pullover","pulp","pulpit","pulsate","pulse","puma","pumice","pummel",
"pump","pumpkin","pun","punch","punctual","puncture","pungent","punish",
"punt","puny","pup","pupil","puppet","puppy","purchase","pure",
"purge","purity","purple","purpose","purr","purse","pursue","pus",
"push","pushover","put","putrid","putter","putty","puzzle","pyramid",
"pyre","python","quack","quail","quaint","quake","qualify","quality",
"qualm","quandary","quantity","quarrel","quarry","quart","quarter","quartz",
"quaver","quay","queasy","queen","queer","quell","quench","query",
"quest","question","quibble","quick","quicken","quickly","quiet","quill",
"quilt","quirk","quit","quite","quitter","quiver","quiz","quorum",
"quota","quote","quotient","rabbi","rabbit","rabble","rabid","rabies",
"raccoon","race","racial","rack","racket","racy","radar","radiance",
"radiant","radiate","radiator","radical","radii","radio","radish","radius",
"raffle","raft","rafter","rag","rage","ragged","raid","raider",
"rail","railroad","rain","rainbow","raincoat","rainy","raise","raisin",
"rake","rally","ram","ramble","ramp","rampage","rampant","ran",
"ranch","rancher","rancid","rancor","random","range","ranger","rank",
"rankle","ransack","ransom","rant","rap","rape","rapid","rapidity",
"rapidly","rapt","rapture","rare","rarely","rarity","rascal","rash",
"rat","rate","rather","ratify","rating","ratio","ration","rattle",
"raucous","ravage","rave","raven","ravenous","ravine","raw","ray",
"rayon","raze","razor","re","reach","react","reaction","reactor",
"read","readable","reader","readily","reading","ready","real","realism",
"realize","really","realm","realty","ream","reap","rear","reason",
"reassure","rebate","rebel","rebirth","rebound","rebuff","rebuild","rebuke",
"rebut","recall","recede","receipt","receive","receiver","recent","recently",
"recess","recipe","recital","reckless","reckon","reclaim","recline","recoil",
"record","recorder","recount","recourse","recover","recruit","rectify","rectum",
"recur","recycle","red","redden","redeem","redhead","reduce","reed",
"reef","reek","reel","refer","referee","refill","refine","refinery",
"reflect","reflex","reform","reformer","refrain","refresh","refuge","refugee",
"refund","refusal","refuse","refute","regain","regal","regard","regatta",
"regent","regime","regiment","region","regional","register","registry","regret",
"regulate","rehearse","reign","rein","reindeer","reject","rejoin","relate",
"related","relation","relative","relax","relay","release","relent","relevant",
"reliable","reliance","relic","relief","relieve","religion","relish","relive",
"rely","remain","remains","remark","remedial","remedy","remember","remind",
"reminder","remiss","remit","remorse","remote","remotely","removal","remove",
"rend","render","renegade","renew","renewal","renounce","renown","renowned",
"rent","rental","repair","repeal","repeat","repel","repent","replace",
"replete","reply","report","repress","reprieve","reprisal","reproach","republic",
"repulse","repute","request","require","rescue","rescuer","research","resent",
"reserve","reserved","reside","resident","resign","resin","resist","resolute",
"resolve","resonant","resort","resound","respect","respite","respond","response",
"rest","restive","restless","restore","restrain","restrict","result","resume",
"retail","retailer","retain","retard","retch","retina","retire","retort",
"retrace","retract","retreat","retrieve","return","reunion","reunite","rev",
"reveal","revel","revelry","revenue","revere","reverent","reverie","reversal",
"reverse","revert","review","reviewer","revile","revise","revival","revive",
"revoke","revolt","revolve","revolver","revue","reward","rhapsody","rhyme",
"rhythm","rib","ribbon","rice","rich","riches","richly","ricochet",
"rid","riddle","ride","rider","ridge","ridicule","rifle","rift",
"rig","right","rightful","rightly","rigid","rigidly","rigor","rigorous",
"rim","rind","ring","rink","rinse","riot","rip","ripe",
"ripen","ripple","rise","risen","riser","risk","risky","rite",
"ritual","rival","rivalry","river","rivet","roach","road","roadside",
"roam","roar","roast","rob","robber","robe","robin","robot",
"robust","rock","rocker","rocket","rocky","rod","rode","rodent",
"rodeo","roe","rogue","role","roll","roller","romance","romantic",
"romp","roof","roofing","rookie","room","roomy","roost","rooster",
"root","rope","rose","roster","rosy","rot","rotary","rotate",
"rotation","rotor","rotten","rotund","rouge","rough","round","rouse",
"rout","route","routine","row","rowboat","rowdy","royal","rub",
"rubber","rubbish","rubble","ruby","ruckus","rudder","ruddy","rude",
"rudely","rudeness","rue","rueful","ruffle","rug","rugged","ruin",
"ruinous","rule","ruler","rum","rumble","ruminate","rummage","rumor",
"rump","rumple","run","runaway","rung","runner","runny","runway",
"rupture","rural","ruse","rush","rust","rustic","rustle","rusty",
"rut","ruthless","rye","saber","sabotage","sack","sacred","sad",
"sadden","saddle","sadly","sadness","safe","safety","sag","saga",
"sage","said","sail","sailor","saint","sake","salable","salad",
"salary","sale","salesman","saliva","sallow","salmon","saloon","salt",
"salty","salute","salvage","salve","same","sameness","sample","sand",
"sandal","sandbag","sandman","sandwich","sandy","sane","sanitary","sanity",
"sank","sap","sapling","sapphire","sarcasm","sash","Satan","satin",
"satire","satisfy","saturate","sauce","saucer","sausage","savage","save",
"savory","saw","say","saying","scab","scaffold","scald","scale",
"scallop","scalp","scan","scandal","scant","scar","scarce","scarcely",
"scarcity","scare","scarf","scary","scatter","scene","scenic","scent",
"schedule","scheme","school","science","scissors","scoff","scold","scoop",
"scoot","scope","scorch","score","scorn","Scotch","scour","scourge",
"scout","scowl","scram","scramble","scrap","scrape","scratch","scratchy",
"scrawl","scrawny","scream","screech","screen","screw","scribble","scribe",
"script","scroll","scrub","scuff","scuffle","sculptor","scum","scurry",
"scuttle","sea","seal","seam","sear","search","seashell","seashore",
"seasick","season","seasonal","seat","second","secrecy","secret","secrete",
"sect","section","sector","secure","security","sedan","sedative","sediment",
"seduce","see","seed","seedy","seek","seem","seep","seethe",
"segment","seize","seizure","seldom","select","self","selfish","sell",
"seller","selves","seminary","senate","senator","send","senior","sense",
"sensible","sensual","sensuous","sent","sentence","separate","sequel","sequence",
"serenade","serene","serenity","sergeant","serial","series","sermon","serpent",
"serum","servant","serve","service","servile","session","set","setback",
"setting","settle","settler","seven","sever","several","severe","severely",
"sew","sewage","sewer","sex","sexual","shabbily","shabby","shack",
"shackle","shade","shadow","shadowy","shady","shaft","shaggy","shake",
"shaky","shall","shallow","sham","shambles","shame","shameful","shampoo",
"shamrock","shanty","shape","shapely","share","shark","sharp","sharpen",
"sharply","shave","shawl","she","sheaf","shear","sheath","sheathe",
"shed","sheen","sheep","sheer","sheet","shelf","shell","shelter",
"shelve","shelves","shepherd","sheriff","shield","shift","shifty","shimmer",
"shin","shine","ship","shipping","shirk","shirt","shiver","shoal",
"shock","shocking","shod","shoddy","shoe","shoelace","shook","shoot",
"shop","shopper","shore","short","shortage","shorten","shortly","shot",
"shotgun","should","shoulder","shout","shove","shovel","show","showcase",
"shower","showman","shown","showy","shrapnel","shred","shrewd","shriek",
"shrill","shrimp","shrine","shrink","shrivel","shroud","shrub","shrug",
"shuck","shudder","shun","shunt","shut","shutter","shuttle","shy",
"sick","sicken","sickle","sickly","sickness","side","sideshow","sidestep",
"sidewalk","siding","sidle","siege","sieve","sift","sigh","sight",
"sign","signal","signpost","silence","silent","silk","silken","sill",
"silly","silver","similar","simmer","simple","simplify","simply","sin",
"since","sincere","sinew","sinewy","sinful","sing","singe","singer",
"single","singly","singular","sink","sip","siphon","sir","sire",
"siren","sirloin","sister","sisterly","sit","site","six","sixty",
"sizable","size","sizzle","skate","skeleton","sketch","sketchy","ski",
"skid","skill","skillful","skim","skimp","skimpy","skin","skinny",
"skip","skirmish","skirt","skit","skittish","skull","skunk","sky",
"skylight","skyline","slab","slack","slacken","slain","slake","slam",
"slander","slang","slant","slap","slash","slat","slate","slave",
"slavery","slavish","slay","sled","sleek","sleep","sleeper","sleepy",
"sleet","sleeve","sleigh","slender","slept","slew","slice","slick",
"slid","slide","slight","slim","slime","slimy","sling","slink",
"slip","slippery","slit","slither","sliver","slob","slobber","slogan",
"slop","slope","sloppy","slosh","slot","sloth","slouch","slovenly",
"slow","sludge","slug","sluggish","slum","slumber","slump","slung",
"slunk","slur","slush","sly","smack","small","smallpox","smart",
"smash","smear","smell","smile","smith","smock","smog","smoke",
"smoker","smoky","smolder","smooth","smother","smudge","smug","smuggle",
"smuggler","smut","snack","snag","snail","snake","snap","snappy",
"snapshot","snare","snarl","snatch","sneak","sneer","sneeze","snicker",
"snide","sniff","sniffle","snip","snipe","sniper","snob","snobbish",
"snoop","snooze","snore","snort","snout","snow","snowplow","snowy",
"snub","snuff","snug","so","soak","soap","soapy","soar",
"sob","sober","soccer","sociable","social","sock","socket","sod",
"soda","sodium","sofa","soft","soften","soggy","soil","sojourn",
"solar","sold","solder","soldier","sole","solely","solemn","solicit",
"solid","solidify","solidity","solitary","solitude","solo","soloist","solution",
"solve","solvent","somber","some","somebody","somehow","sometime","somewhat",
"son","sonata","song","soon","soot","soothe","soprano","sorcerer",
"sorcery","sordid","sore","sorely","sorority","sorrow","sorry","sort",
"soul","sound","soup","sour","source","south","southern","souvenir",
"sow","sown","space","spade","span","spaniel","spank","spar",
"spare","spark","sparkle","sparkler","sparrow","sparse","spasm","spat",
"spatial","spatter","spatula","spawn","speak","speaker","spear","species",
"specific","specify","specimen","speck","specter","sped","speech","speed",
"speedy","spell","spend","spent","sperm","spew","sphere","spice",
"spicy","spider","spike","spill","spin","spindly","spine","spinster",
"spiral","spire","spirit","spit","spite","spiteful","splash","splendid",
"splendor","splint","splinter","split","spoil","spoke","spoken","sponge",
"sponsor","spook","spooky","spool","spoon","spoonful","sport","spot",
"spotless","spotty","spouse","spout","sprain","sprang","sprawl","spray",
"spread","spree","sprig","spring","sprinkle","sprint","sprout","spruce",
"sprung","spry","spun","spur","spurn","spurt","sputter","spy",
"squad","squalid","squall","squalor","squander","square","squash","squat",
"squawk","squeak","squeaky","squeal","squid","squint","squirm","squirrel",
"squirt","stab","stable","stack","stadium","staff","stag","stage",
"stagger","stagnant","stagnate","stain","stair","stairway","stake","stale",
"stalk","stall","stallion","stalwart","stamina","stammer","stamp","stampede",
"stance","stand","standard","standing","staple","stapler","star","starch",
"starchy","stare","starfish","stark","start","starter","startle","starve",
"state","static","station","statue","stature","status","statute","staunch",
"stave","stay","steady","steak","steal","steam","steel","steep",
"steeple","steer","stem","stencil","step","stereo","sterile","sterling",
"stern","stew","steward","stick","sticker","sticky","stiff","stiffen",
"stifle","stigma","still","stilted","stimuli","stimulus","sting","stingy",
"stink","stint","stir","stirrup","stitch","stock","stockade","stocking",
"stocky","stole","stolen","stomach","stomp","stone","stony","stood",
"stool","stoop","stop","stopover","stoppage","stopper","storage","store",
"stork","storm","stormy","story","stout","stove","stow","stowaway",
"straddle","straggle","straight","strain","strainer","strait","strand","strange",
"stranger","strangle","strap","strata","stratum","straw","stray","streak",
"stream","street","stress","stretch","strew","strict","stride","strife",
"strike","striking","string","strip","stripe","strive","striven","stroke",
"stroll","strong","strongly","struck","struggle","strum","strut","stub",
"stubble","stubborn","stuck","stud","student","studio","studious","study",
"stuff","stuffing","stuffy","stumble","stump","stun","stung","stunning",
"stunt","stupid","stupor","sturdy","style","stylish","subdue","subject",
"sublime","submerge","submit","subside","subsist","subtle","subtract","suburb",
"subway","succeed","success","succor","succumb","such","suck","sucker",
"suction","sudden","suddenly","suds","sue","suede","suffer","sugar",
"suggest","suicide","suit","suitable","suitably","suitcase","suite","suitor",
"sulfur","sulk","sulky","sullen","sultan","sultry","sum","summary",
"summer","summit","summon","summons","sun","sunbathe","sunburn","sundae",
"Sunday","sundown","sunk","sunken","sunlight","sunlit","sunny","sunrise",
"sunset","sunshine","super","superb","superior","supper","supplant","supple",
"supply","support","suppress","supreme","sure","surely","surf","surface",
"surfing","surge","surgeon","surgery","surgical","surly","surmise","surmount",
"surplus","surprise","survey","survival","survive","survivor","suspect","suspend",
"sustain","swab","swagger","swallow","swam","swamp","swan","swap",
"swarm","swarthy","swat","sway","swear","sweat","sweater","sweep",
"sweeping","sweet","sweeten","swell","swelling","swept","swift","swiftly",
"swim","swindle","swindler","swine","swing","swipe","swirl","swish",
"switch","swollen","swoon","swoop","sword","swore","sworn","swum",
"swung","syllable","symbol","symbolic","symmetry","symphony","synonym","syntax",
"syringe","syrup","system","tab","table","tablet","tabulate","tacit",
"tack","tackle","taco","tact","tactful","tadpole","tag","tail",
"tailor","taint","take","taken","takeoff","tale","talent","talented",
"talk","talker","tall","tally","talon","tame","tamper","tan",
"tandem","tangible","tangle","tank","tanker","tantrum","tap","tape",
"taper","tapestry","tar","target","tariff","tarnish","tarry","tart",
"tartar","task","tassel","taste","tasteful","tattle","tattoo","taught",
"taunt","taut","tavern","tawny","tax","taxation","taxi","tea",
"teach","teacher","teaching","teacup","teak","team","teamwork","teapot",
"tear","tease","teaspoon","teat","tedious","tee","teem","teeter",
"teeth","teethe","telegram","televise","tell","teller","temper","tempest",
"temple","tempo","tempt","ten","tenant","tend","tendency","tender",
"tendon","tenement","tennis","tenor","tense","tension","tent","tepee",
"tepid","term","terminal","termite","terrain","terrible","terribly","terrier",
"terrific","terror","terse","tersely","test","testify","tetanus","tether",
"text","textile","texture","than","thank","thankful","that","thatch",
"thaw","the","theater","theft","their","theirs","them","theme",
"then","theology","theory","therapy","there","thereof","these","thesis",
"they","thick","thicken","thickly","thief","thigh","thimble","thin",
"thing","think","thinly","third","thirst","thirsty","thirteen","thirty",
"this","thistle","thong","thorn","thorny","those","though","thought",
"thousand","thrash","thread","threat","threaten","three","thresh","thresher",
"threw","thrift","thrill","thriller","thrive","throat","throb","throne",
"throng","throttle","through","throw","thrown","thrust","thud","thug",
"thumb","thump","thunder","thus","thwart","thyroid","tick","ticket",
"tickle","ticklish","tidal","tidbit","tide","tidy","tie","tier",
"tiger","tight","tightly","tights","tile","till","tilt","timber",
"time","timely","timer","timid","tin","tingle","tinker","tinkle",
"tinsel","tint","tiny","tip","tiptoe","tire","tired","tireless",
"tissue","tit","title","to","toad","toast","toaster","tobacco",
"today","toddler","toe","toenail","together","toil","toilet","token",
"tolerant","toll","tomahawk","tomato","tomb","tomboy","tomcat","tomorrow",
"ton","tone","tongs","tongue","tonic","tonight","tonnage","tonsil",
"too","took","tool","toot","tooth","top","topic","topple",
"torch","tornado","torpedo","torso","tortilla","tortoise","tortuous","torture",
"toss","tot","total","totally","tote","totter","touch","touchy",
"tough","toughen","tour","tousle","tow","toward","towel","tower",
"town","toxic","toxin","toy","trace","track","tract","tractor",
"trade","trader","tragedy","tragic","trail","trailer","train","trait",
"traitor","tramp","trance","tranquil","transact","transfer","transit","trap",
"trapeze","trapper","trash","travel","traveler","traverse","trawl","trawler",
"tray","tread","treason","treasure","treasury","treat","treaty","treble",
"tree","trek","trellis","tremble","tremor","trench","trend","trespass",
"trestle","trial","triangle","tribal","tribe","tribunal","tribute","trick",
"trickery","tricky","tricycle","tried","trifle","trigger","trill","trillion",
"trim","trio","trip","tripe","triple","triplet","tripod","trite",
"triumph","trod","trodden","troll","trolley","trombone","troop","trooper",
"trophy","tropical","trot","trouble","trough","trounce","troupe","trousers",
"trout","truant","truce","truck","trudge","true","truly","trumpet",
"trunk","trust","trustee","truth","truthful","try","trying","tryout",
"tub","tuba","tube","tubular","tuck","Tuesday","tuft","tug",
"tuition","tulip","tumble","tumbler","tummy","tumor","tumult","tuna",
"tundra","tune","tuner","tunic","tunnel","turban","turbine","turf",
"turkey","turn","turnip","turnout","turnpike","turtle","tusk","tussle",
"tutor","twang","tweak","tweed","tweet","tweezers","twelve","twenty",
"twice","twig","twilight","twin","twine","twinge","twinkle","twirl",
"twist","twitch","twitter","two","tycoon","type","typhoon","typical",
"typify","typist","tyranny","tyrant","udder","ugliness","ugly","ulcer",
"ulterior","ultimate","umbrella","umpire","unable","unarmed","unaware","unawares",
"unborn","uncanny","uncle","uncommon","uncouth","under","underdog","undo",
"undone","undying","unearth","uneasy","unequal","unfair","unfit","unfold",
"unfurl","ungainly","unhook","unicorn","uniform","unify","union","unique",
"unison","unit","unite","unity","unkind","unknown","unleash","unless",
"unlike","unlikely","unload","unlock","unlucky","unnerve","unpack","unravel",
"unreal","unrest","unruly","unseat","unseemly","unsound","untie","untold",
"unused","unveil","unwieldy","unwind","up","upbeat","upgrade","upheaval",
"uphill","uphold","upkeep","upon","upper","upright","uprising","uproar",
"upset","upshot","upstairs","upstream","upturn","upward","uranium","urban",
"urchin","urge","urgency","urgent","urinate","urine","urn","us",
"usage","use","used","useful","usefully","useless","user","usher",
"usual","usurp","utensil","uterus","utility","utilize","utmost","utter",
"vacancy","vacant","vacate","vacation","vaccine","vacuum","vagina","vagrant",
"vague","vain","valet","valiant","valid","validate","validity","valley",
"valor","valuable","value","valve","vampire","van","vanguard","vanilla",
"vanish","vanity","vanquish","vapor","vaporize","variable","variant","varied",
"variety","various","varnish","vary","vase","vast","vastly","vat",
"vault","veal","veer","vehement","vehicle","veil","vein","velvet",
"velvety","venerate","venison","venom","venomous","venture","veranda","verb",
"verbal","verbally","verdict","verge","verify","vermin","verse","version",
"versus","vertebra","vertical","very","vessel","vest","vestige","veteran",
"veto","vex","via","viable","viaduct","vial","vibrant","vicar",
"vice","vicinity","vicious","victim","victor","victory","video","vie",
"view","viewer","vigil","vigorous","vile","vilify","villa","village",
"villager","vine","vinegar","vineyard","violate","violence","violent","violet",
"violin","viper","virgin","virile","virtual","virtue","virulent","virus",
"vise","visible","visibly","vision","visit","visitor","visor","vista",
"visual","vital","vitality","vitally","vitamin","vivacity","vivid","vocal",
"vocalist","vocation","vodka","vogue","voice","void","volatile","volcanic",
"volcano","volition","volley","volt","voltage","volume","vomit","vote",
"voter","vouch","vow","vowel","voyage","vulgar","vulture","wad",
"waddle","wade","wafer","waffle","waft","wag","wage","wager",
"wagon","waif","wail","waist","wait","waiter","waitress","waive",
"wake","waken","walk","walker","wall","wallet","wallop","wallow",
"walnut","walrus","waltz","wan","wand","wander","wanderer","wane",
"want","wanton","war","warble","ward","warden","wardrobe","warfare",
"warm","warmly","warmth","warn","warning","warp","warrant","warrior",
"wart","wary","was","wash","washer","washing","wasp","waste",
"wasteful","watch","watchdog","watchful","water","waterway","watery","watt",
"wave","waver","wavy","wax","way","waylay","wayside","wayward",
"we","weak","weaken","weakling","weakly","weakness","wealth","wealthy",
"wean","weapon","wear","wearily","weary","weasel","weather","weave",
"web","wed","wedge","wedlock","weed","week","weekday","weekend",
"weekly","weep","weigh","weight","weighty","weird","welcome","weld",
"welder","welfare","well","went","wept","were","we're","werewolf",
"west","westerly","westward","wet","whack","whale","whaler","wharf",
"what","whatever","wheat","wheel","wheeze","when","whenever","where",
"whereas","wherein","wherever","whether","which","whiff","while","whim",
"whimper","whinny","whip","whir","whirl","whisk","whisker","whiskey",
"whistle","white","whittle","whiz","who","whoa","whoever","whole",
"wholly","whom","whoop","whose","why","wick","wicked","wicker",
"wide","widely","widen","widow","widower","width","wield","wife",
"wig","wiggle","wild","wildlife","will","willful","willing","willow",
"wilt","wily","win","wince","winch","wind","windfall","windmill",
"window","windy","wine","wing","wink","winner","winning","winsome",
"winter","wipe","wire","wiry","wisdom","wise","wisely","wish",
"wisp","wistful","wit","witch","with","withdraw","wither","withhold",
"within","without","witness","witty","wives","wizard","wobble","wobbly",
"woe","wolf","wolves","woman","womb","women","won","wonder",
"wont","won't","woo","wood","wooded","wooden","woodland","woodwind",
"woodwork","woody","woof","wool","word","wording","wordy","wore",
"work","workable","worker","workout","workshop","world","worldly","worm",
"worn","worry","worse","worsen","worst","worth","worthy","would",
"wound","wove","woven","wrangle","wrap","wrapper","wrath","wreak",
"wreath","wreck","wreckage","wren","wrench","wrest","wrestle","wretch",
"wretched","wriggle","wring","wringer","wrinkle","wrist","writ","write",
"writer","writhe","writing","wrong","wrote","wrought","wrung","wry",
"Xmas","yacht","yak","yam","yank","Yankee","yap","yard",
"yawn","year","yearling","yearly","yearn","yearning","yeast","yell",
"yellow","yelp","yes","yet","yield","yodel","yoke","yokel",
"yolk","yonder","you","young","your","yours","yourself","youth",
"youthful","zany","zeal","zealous","zebra","zero","zest","zigzag",
"zinc","zip","zipper","zodiac","zone","zoo","zoology","zoom"];
//Final word count: 8192, before prune: 8667
